export { default as PageGestionCitas } from './PageGestionCitas/PageGestionCitas';
export { default as PageGestionHorarios } from './PageGestionHorario/PageGestionHorarios';
export { default as PageConfiguracion } from './pageConfiguracion/PageConfiguracion';
export { default as PageDashboard } from './pageDashboard/PageDashboard';
export { default as PageGestionPacientes } from './pageGestionPacientes/PageGestionPacientes';
export * from './pageGestionPacientesData';
export { default as PageArchivos } from './pageGestionPacientesData/pageArchivos/PageArchivos';
export { default as PageDatosPersonales } from './pageGestionPacientesData/pageDatosPersonales/PageDatosPersonales';
export { default as PageHistorialClinica } from './pageGestionPacientesData/pageHistorialClinica/PageHistorialClinica';
export { default as PageHistorialDecitas } from './pageGestionPacientesData/pageHistorialDeCitas/PageHistorialDecitas';
export { default as PageHistorialDelPaciente } from './pageGestionPacientesData/pageHistorialDelPaciente/PageHistorialDelPaciente';
export { default as PageGestionServicios } from './pageGestionServicios/PageGestionServicios';
export { default as PageGestionUsuarios } from './pageGestionUsuarios/PageGestionUsuarios';
export { default as PageHome } from './pageHome/PageHome';
export { default as PageGestionMedicos } from './pageMedicos/PageGestionMedicos';
export { default as PageReportes } from './pageReportes/PageReportes';
